api: ["1.0.9"]
name: Examination
version: 1.0
author: Zao_hon
main: cn.blockmc.Zao_hon.Examination.Examination
depend:
  - FormAPI
commands:
  Examination:
    description: exam command
    usage: "/exam help"
    aliases: ["exam"]